### ISSUE TITLE
Problems with right-shift in Gear rollsum.

### ISSUE THREAD

**Issue by dbaarda** [iscc/fastcdc-py#12]
This implementation copies another implementation that uses a right-shift in its Gear rollsum. This has problems I reported here;

https://github.com/ronomon/deduplication/issues/7

**Comment by titusz** [comment]
My priority is compatibility with the majority of implementations. I am happy to adjust this implementation if the upstream or the majority of other implementations changes. I think it is valuable to have compatibility for a broad number languages.
