### ISSUE TITLE
Query Regarding the Safety of FastCDC in a Multiprocessing Environment

### ISSUE THREAD

**Issue by kcunitary** [iscc/fastcdc-py#18]
Dear FastCDC Developers,
Hello! I am currently using the FastCDC library for some project development and I greatly appreciate your work.

I have a question that I would like to ask. I am considering using multiprocessing in my project, but I am unsure if the FastCDC library can safely operate in a multiprocessing environment. I did not find related information in the documentation, so I thought to inquire here.

If the FastCDC library can safely operate in a multiprocessing environment, are there any special steps or precautions that need to be taken to ensure its safety? If not, could you recommend any alternatives or solutions?

Thank you very much for your assistance! I look forward to your reply.

**Comment by titusz** [comment]
It depends on what you are trying to do. Processing multiple files in separate processes in parallel should work fine. Processing a single file in parallel using multiple processes is not supported. Does that answer your question?

**Comment by kcunitary** [comment]
Thank you very much for your prompt and informative response. It has indeed answered my question.
