### ISSUE TITLE
Python 3.12 & pip

### ISSUE THREAD

**Issue by Torxed** [iscc/fastcdc-py#21]
Hi.

Could we get a new **pip** release that targets `Python 3.12.3` or at least `>=3.12`?
It's the latest stable and the current pip release does not allow for targeting 3.12 on windows:

```
$ pip download --verbose --python-version=3.12 --only-binary=":all:" --platform win_amd64 --dest ~/Downloads/ "fastcdc==1.5.0"
```

Could skip using `--only-binary` and use the source to get around it. But that could put additional requirements on the target system installing the package so having the option to get the binary would be nice.

**Comment by titusz** [comment]
I made a new release 1.6.0 including Python 3.12 binaries. Please let me know if that works for you.

**Comment by Torxed** [comment]
That did the trick, superb turnaround! Thank you!
