### ISSUE TITLE
Cython version does not appear to pass correct data when using 'fat' option.

### ISSUE THREAD

**Issue by bolapara** [iscc/fastcdc-py#9]
I've noticed that the 'fat' option appears to be broken when using the Cython version of the library.  The pure Python version appears to work correctly.  I have not had time to investigate why the Cython version returns different data than the Python version (And I'm not very familiar with Cython anyway).  I've added a test to expose the problem and will submit a PR for it.  #8 

fastcdc 1.4.0
Cython version 0.29.21
Python 3.8.2
Ubuntu 20.04 x64 based distro.

**Comment by titusz** [comment]
Thanks for catching this ugly bug and providing tests. I am also new to Cython :). I have fixed the issue and released a new version on pypi.
